DROP TABLE SIMPLE;


CREATE TABLE SIMPLE (
    BNO NUMBER PRIMARY KEY,
    BWRITER VARCHAR2(50),
    BTITLE   VARCHAR2(100),
    BCONTENT  VARCHAR2(100),
    BDATE DATE
    );
DROP  SEQUENCE SIMPLE_SEQ;
CREATE SEQUENCE SIMPLE_SEQ
START WITH 1     
INCREMENT BY 1 
MAXVALUE 99999
NOCYCLE
NOCACHE
;
INSERT INTO SIMPLE(BNO,BWRITER,BTITLE,BCONTENT,BDATE)
VALUES (SIMPLE_SEQ.NEXTVAL,'한예슬','공지사항','큐알체크',SYSDATE);
COMMIT
