DROP TABLE BOARD;
DROP TABLE MEMBER;
CREATE TABLE MEMBER (
	MNO NUMBER PRIMARY KEY,
	MID VARCHAR2(20) NOT NULL,
	MNAME VARCHAR2(20)
);

DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;


INSERT INTO MEMBER (MNO, MID, MNAME) VALUES (MEMBER_SEQ.NEXTVAL,'EMILY','에밀리');
INSERT INTO MEMBER (MNO, MID, MNAME) VALUES (MEMBER_SEQ.NEXTVAL,'BOND','본드');
COMMIT