DROP TABLE CONTACT;
CREATE TABLE CONTACT (
	CNO NUMBER PRIMARY KEY,
	CNAME VARCHAR2(50),
	CPHONE VARCHAR2(50),
	CADDRESS VARCHAR2(100),
	CEMAIL VARCHAR2(100),
	CNOTE VARCHAR2(1000)
);


DROP SEQUENCE CONTACT_SEQ;
CREATE SEQUENCE CONTACT_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 999999
NOCYCLE
NOCACHE;

INSERT INTO CONTACT (CNO, CNAME, CPHONE, CADDRESS, CEMAIL, CNOTE)
VALUES (CONTACT_SEQ.NEXTVAL, '에밀리', '010-1111-1111', '서울시 마포구', 'emily@com.com', '친한친구');
COMMIT

SELECT CNO, CNAME, CPHONE, CADDRESS, CEMAIL, CNOTE FROM CONTACT;
