DROP TABLE WHITE;
CREATE TABLE WHITE(
	NO NUMBER PRIMARY KEY, --기본키
	ID VARCHAR2(100) NOT NULL UNIQUE,
	PW VARCHAR2(100) NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	AGE NUMBER,
	EMAIL VARCHAR2(100) NOT NULL UNIQUE,
	REG_DATE DATE
);

DROP SEQUENCE WHITE_SEQ;
CREATE SEQUENCE WHITE_SEQ;

INSERT INTO WHITE VALUES(WHITE_SEQ.NEXTVAL,'admin','1111','제임스',40,'admin@white.com',SYSDATE);
INSERT INTO WHITE VALUES(WHITE_SEQ.NEXTVAL,'id01','1111','에밀리',40,'emily@white.com',SYSDATE);

SELECT ID, NO FROM WHITE;
select * FROM WHITE;
