DROP SEQUENCE MEMBER_SEQ;
DROP SEQUENCE BOARD_SEQ;

CREATE SEQUENCE MEMBER_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCYCLE NOCACHE;
CREATE SEQUENCE BOARD_SEQ START WITH 1 INCREMENT BY 1 MAXVALUE 999999 NOCYCLE NOCACHE;

DROP TABLE BOARD;
DROP TABLE MEMBER;

CREATE TABLE MEMBER(
	MNO NUMBER PRIMARY KEY,
	MID VARCHAR2(30) NOT NULL UNIQUE,
	MPW VARCHAR2(30) NOT NULL,
	MNAME VARCHAR2(30) NOT NULL,
	MEMAIL VARCHAR2(100) NOT NULL UNIQUE,
	MPHONE VARCHAR2(15),
	MADDRESS VARCHAR2(100),
	MREGDATE DATE	
);

CREATE TABLE BOARD(
 	BNO NUMBER PRIMARY KEY,
 	MNO NUMBER REFERENCES MEMBER (MNO), --MEMBER테이블의 MNO칼럼을 참조하는 외래키
 	BTITLE VARCHAR2(1000) NOT NULL,
	BCONTENT VARCHAR2(2000),
	BPW VARCHAR2(30),
	BIP VARCHAR2(30),
	BHIT NUMBER,
	BREF NUMBER, --REF
	BSTEP NUMBER, --STEP
	BDEPTH NUMBER, --DEPTH
	BDELETE NUMBER,--삭제여부, 정상0, 삭제-1
	BREGDATE DATE
	
);

INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL,'admin','1111','관리자','admin@myhome.com','010-0000-0000','서울시 마포구',SYSDATE);
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL,'user1','1111','홍길동','user1@myhome.com','010-0000-0000','서울시 중구',SYSDATE);
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL,'user2','1111','강호동','user2@myhome.com','010-0000-0000','부천시',SYSDATE);
INSERT INTO MEMBER VALUES(MEMBER_SEQ.NEXTVAL,'user3','1111','유재석','user3@myhome.com','010-0000-0000','광명시',SYSDATE);

COMMIT

